export const GET_ALL_STATIONS = 'Home/GET_ALL_STATIONS';
export const SET_STATIONS = 'Home/SET_STATIONS';
export const GET_LATEST_DATE_SCHEDULE = 'Home/GET_LATEST_DATE_SCHEDULE';
export const SET_LATEST_DATE_SCHEDULE = 'Home/SET_LATEST_DATE_SCHEDULE';
