spring:
  config:
    activate:
      on-profile: default
  dotenv:
    enabled: true
  datasource:
    url: ${DATABASE_DEV_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_NODEMAILER}
    password: ${PASSWORD_NODEMAILER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  port: ${PORT:8080}
  jwt-secret: ${JWT_SECRET}

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${DATABASE_TEST_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_NODEMAILER}
    password: ${PASSWORD_NODEMAILER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  jwt-secret: ${JWT_SECRET}

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${DATABASE_PROD_URL}
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_NODEMAILER}
    password: ${PASSWORD_NODEMAILER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  port: ${PORT:8080}
  jwt-secret: ${JWT_SECRET}