export const GET_ALL_STATIONS = 'Gate/GET_ALL_STATIONS';
export const SET_STATIONS = 'Gate/SET_STATIONS';
export const VALIDATE_TICKET_ON_DEPARTURE = 'Gate/VALIDATE_TICKET_ON_DEPARTURE';
export const VALIDATE_TICKET_ON_ARRIVAL = 'Gate/VALIDATE_TICKET_ON_ARRIVAL';
export const SET_VALIDATE_RESULT = 'Gate/SET_VALIDATE_RESULT';
